import type { VertoConfig, FieldMappings, DisplayStatusGroup, GitHubConfig } from '@verto/config'
import { mergeConfigs } from '@verto/config'
import { requireGitHubConfig } from './githubConfig.js'
import { githubAdapterDefaults } from './defaults.js'
import { gqlRequest } from './gqlRequest.js'
import { statusOptionsFromProjectFields, seedCanonicalProjectV2FieldMapping, resolveProjectV2FieldName } from './projectField.js'

export interface AuditOptions {
  /** When true, seed repository-scope issueFilter / includeClosedAncestors if absent. */
  seedRepoDefaults?: boolean
}

export interface AuditResult {
  /** Partial config object suitable for passing to mergeConfigs() */
  discovered: Partial<VertoConfig>
  /** Non-fatal informational messages collected during audit */
  warnings: string[]
}

const ISSUE_NATIVE_MAPPINGS: FieldMappings = Object.fromEntries(
  Object.entries(githubAdapterDefaults.github?.fieldMappings ?? {}).filter(
    ([, e]) => e.from.kind === 'issue',
  ),
)

export function buildWizardConfigComments(scope: 'project' | 'repository'): string {
  const lines = [
    '// Verto workspace configuration — generated by setup wizard.',
    '// Edit fieldMappings, displayStatusGroups, and filters to match your workflow.',
    '',
    '// Optional overrides (uncomment and customize as needed):',
    '// "priority" — map select/number field values to 1–9 (see DESIGN.md §4.6.3)',
    '// "isDeliverySlice" — label or field rule marking vertical slices',
    '// "personas" — map labels like persona:pm to persona fields',
  ]
  if (scope === 'repository') {
    lines.push(
      '',
      '// Repository scope loads OPEN issues by default (github.issueFilter).',
      '// GitHub cannot filter by parent/child — includeClosedAncestors walks upward',
      '// to include closed parent issues of open children.',
      '// Narrow large repos: uncomment labels or milestone in issueFilter.',
      '//   "issueFilter": { "states": ["OPEN"], "labels": ["your-label"] }',
    )
  }
  return lines.join('\n') + '\n'
}

function mergeIssueNativeDefaults(mappings: FieldMappings): FieldMappings {
  return { ...ISSUE_NATIVE_MAPPINGS, ...mappings }
}

/** User display groups from audited Status options (first → Raw, middle → In Progress; last is Done via node.isDone). */
export function buildProjectDisplayStatusGroups(statusOptions: string[]): DisplayStatusGroup[] {
  if (statusOptions.length === 0) {
    return [{ label: 'Raw', sources: { parsed: { statuses: ['raw'] } } }]
  }

  const first = statusOptions[0]!
  const middle = statusOptions.length > 2 ? statusOptions.slice(1, -1) : []

  const groups: DisplayStatusGroup[] = []

  if (middle.length > 0) {
    groups.push({
      label: 'In Progress',
      sources: { ticket: { statuses: middle } },
    })
  }

  groups.push({
    label: 'Raw',
    sources: {
      ticket: { statuses: [first] },
      parsed: { statuses: ['raw'] },
    },
  })

  return groups
}

/**
 * Audits a GitHub ProjectV2 and returns a discovered config fragment with
 * fieldMappings and displayStatusGroups seeded from the project's fields.
 */
export async function auditProjectScope(
  token: string,
  config: VertoConfig,
  _options?: AuditOptions,
): Promise<AuditResult> {
  const github = requireGitHubConfig(config)
  if (github.scope !== 'project') {
    throw new Error('auditProjectScope requires config.github.scope === "project"')
  }

  const warnings: string[] = []
  const ownerField = github.ownerType === 'organization' ? 'organization' : 'user'

  const data = await gqlRequest(
    token,
    `query($owner: String!, $number: Int!) {
      ${ownerField}(login: $owner) {
        projectV2(number: $number) {
          fields(first: 100) {
            nodes {
              __typename
              ... on ProjectV2FieldCommon { name dataType }
              ... on ProjectV2SingleSelectField { options { name } }
            }
          }
        }
      }
    }`,
    { owner: github.owner, number: github.projectNumber },
  )

  const project = (data as Record<string, {
    projectV2?: {
      fields: {
        nodes: Array<{
          name?: string
          dataType?: string
          options?: Array<{ name: string }>
        }>
      }
    }
  }>)[ownerField]?.projectV2
  if (!project) {
    throw new Error('Project not found. Check owner, projectNumber, and ownerType.')
  }

  const fieldMappings: FieldMappings = {}

  for (const field of project.fields.nodes) {
    if (!field.name || field.name === 'Title') continue
    const entry: FieldMappings[string] = { from: { kind: 'projectV2', field: field.name } }
    if (field.dataType === 'SINGLE_SELECT') entry.type = 'select'
    if (field.dataType === 'NUMBER') entry.type = 'number'
    if (field.dataType === 'DATE') entry.type = 'date'
    if (field.dataType === 'ITERATION') entry.type = 'iteration'
    fieldMappings[field.name.toLowerCase().replace(/\s+/g, '_')] = entry
  }

  seedCanonicalProjectV2FieldMapping(fieldMappings, project.fields.nodes, 'status', github.fieldMappings)
  seedCanonicalProjectV2FieldMapping(fieldMappings, project.fields.nodes, 'priority', github.fieldMappings, {
    bootstrapFieldName: 'Priority',
  })

  const statusOptions = statusOptionsFromProjectFields(project.fields.nodes, fieldMappings)

  if (!resolveProjectV2FieldName(fieldMappings, 'priority')) {
    warnings.push('No priority field mapping — nodes will default to priority 5')
  }

  const displayStatusGroups = buildProjectDisplayStatusGroups(statusOptions)

  const discovered: Partial<VertoConfig> = {
    adapter: 'github',
    ui: { displayStatusGroups },
    github: {
      scope: 'project',
      owner: github.owner,
      projectNumber: github.projectNumber,
      ...(github.ownerType ? { ownerType: github.ownerType } : {}),
      fieldMappings: mergeIssueNativeDefaults(fieldMappings),
    },
  }

  return { discovered, warnings }
}

/**
 * Audits a GitHub repository and returns a discovered config fragment.
 */
export async function auditRepositoryScope(
  token: string,
  config: VertoConfig,
  options?: AuditOptions,
): Promise<AuditResult> {
  const github = requireGitHubConfig(config)
  if (github.scope !== 'repository') {
    throw new Error('auditRepositoryScope requires config.github.scope === "repository"')
  }

  const warnings: string[] = []

  const data = await gqlRequest(
    token,
    `query($owner: String!, $name: String!) {
      repository(owner: $owner, name: $name) {
        labels(first: 100) {
          nodes { name }
        }
      }
    }`,
    { owner: github.owner, name: github.repository },
  )

  const repo = (data as { repository?: { labels: { nodes: { name: string }[] } } }).repository
  if (!repo) {
    throw new Error('Repository not found. Check owner and repository names.')
  }

  const labels: string[] = repo.labels.nodes.map((l: { name: string }) => l.name)
  if (labels.length > 0) {
    warnings.push(`Available labels (${labels.length}): ${labels.slice(0, 20).join(', ')}${labels.length > 20 ? '…' : ''}`)
    warnings.push('Add labels to github.issueFilter.labels to filter issues by label.')
  }

  const configMappings = github.fieldMappings ?? {}
  const projectV2Gaps = Object.entries(configMappings)
    .filter(([, e]) => e.from.kind === 'projectV2')
    .map(([k]) => k)
  if (projectV2Gaps.length > 0) {
    warnings.push(
      `Excluded ${projectV2Gaps.length} projectV2 fieldMapping(s) not applicable in repository scope: ${projectV2Gaps.join(', ')}`,
    )
  }

  const issueOnlyMappings = Object.fromEntries(
    Object.entries(configMappings).filter(([, e]) => e.from.kind === 'issue'),
  )

  const repoGithub: GitHubConfig & { scope: 'repository' } = {
    scope: 'repository',
    owner: github.owner,
    repository: github.repository,
    ...(github.ownerType ? { ownerType: github.ownerType } : {}),
    fieldMappings: mergeIssueNativeDefaults(issueOnlyMappings),
  }

  if (github.issueFilter !== undefined) {
    repoGithub.issueFilter = github.issueFilter
  } else if (options?.seedRepoDefaults) {
    repoGithub.issueFilter = { states: ['OPEN'] }
  }

  if (github.includeClosedAncestors !== undefined) {
    repoGithub.includeClosedAncestors = github.includeClosedAncestors
  } else if (options?.seedRepoDefaults) {
    repoGithub.includeClosedAncestors = true
  }

  const discovered: Partial<VertoConfig> = {
    adapter: 'github',
    ui: githubAdapterDefaults.ui,
    github: repoGithub,
  }

  return { discovered, warnings }
}

/** Merge defaults + identity config, run scope-appropriate audit. */
export async function auditForWizard(
  token: string,
  identity: VertoConfig,
  options?: AuditOptions,
): Promise<AuditResult> {
  const merged = mergeConfigs(githubAdapterDefaults, identity)
  const github = requireGitHubConfig(merged)
  if (github.scope === 'project') {
    return auditProjectScope(token, merged, options)
  }
  return auditRepositoryScope(token, merged, options)
}
